### ISSUE TITLE
bloc fonctionnel temporaire (N)

### ISSUE THREAD

**Issue by thiegaillard** [MTES-MCT/asgard-manager#5]
Dans la documentation en ligne d'Asgard Manager ([exemple ](https://snum.scenari-community.org/Asgard/Documentation/co/ECR_20_ZonageIhmSchemas.html) ), on voit sur les copies d'écran un bloc fonctionnel temporaire (N) mais on n'en parle pas dans la documentation ni dans Asgard Manager.
Cela ne devrait pas exister ou c'est un futur bloc ?

**Comment by thiegaillard** [comment]
OK, cela peut nous intéresser. Mais je ne vois pas comment on peut créer ces blocs "personnalisé" :
Directement dans Asgard Manager ?
Dans PostgreSQL via une fonction ?

**Comment by WREATCHED** [comment]
Réponse en image, c'est plus simple 
![image](https://user-images.githubusercontent.com/66324136/202159462-10f180d1-80f6-4188-8244-f0a79b766807.png)

**Comment by thiegaillard** [comment]
OK pour la méthode.
Il va falloir voir comment on distribue le QGIS3.INI aux utilisateurs...

**Comment by WREATCHED** [comment]
En utilisant le mécanisme du global_settings.ini sur une ressource partagée
Beaucoup d'échanges ont eu lieu sur ce sujet

**Comment by WREATCHED** [comment]
Si tu as eu les réponses à tes interrogations, Thierry, il serait bon de clore les issues si c'est la cas
